version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 26016:27017
    volumes:
      - /var/lib/docker/volumes/gol/_data
    command: [--auth]
    restart: always
# db.auth({user: "root", pwd: "rootpassword"})
# mongo -u root -p root --authenticationDatabase admin
